services:
    web:
      build: .
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - /var/www/html/vendor
        - /var/www/html/storage
        - /var/www/html/bootstrap
        - build_files:/var/www/html/public/build
      networks:
        - app_network
      depends_on:
        - database
      restart: unless-stopped

    server:
      image: nginx:latest
      ports:
        - 8000:80
      volumes:
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
        - build_files:/var/www/html/public/build
      networks:
        - app_network
      depends_on:
        - web
      restart: always

    database:
      image: mongo:6.0
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=ashrafemon143
        - MONGO_INITDB_ROOT_PASSWORD=bKA1M4MRpJoQTMP3
        - MONGO_INITDB_DATABASE=inventory
      command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
      volumes:
        - mongo_data:/data/db
        - ./mongo-keyfile:/etc/mongo-keyfile:ro
      expose:
        - 27017
      networks:
        - app_network

networks:
    app_network:
        driver: bridge

volumes:
    mongo_data:
    build_files:
        driver: local